### ISSUE TITLE
ironman attack animation frame

### ISSUE THREAD

**Issue by kurie** [Illedan/BOTG-Refree#2]
It's nearly impossible to tell when ironman is attacking. Here's the attack frame:
![](https://github.com/Illedan/BOTG-Refree/raw/5de1a14ec61245a7c8d1938c6daa3e654884cd38/team-1%20project/src/main/resources/view/assets/IM-ATTACK-2.png)
and here's walk-1:
![](https://github.com/Illedan/BOTG-Refree/raw/5de1a14ec61245a7c8d1938c6daa3e654884cd38/team-1%20project/src/main/resources/view/assets/IM-WALK-1.png)

**Comment by Illedan** [comment]
Thx for your feedback, I'll add a little attack indication.
