### ISSUE TITLE
enemy Deadpool not becoming visible when my heros stand in the same bush

### ISSUE THREAD

**Issue by cleanrock** [Illedan/BOTG-Refree#6]
I played some games vs Kikoo and noticed he places his Deadpool in a bush fairly early.
So i made a huntHiddenHero function but noticed that the Deadpool was not revealed when both my heros stood in the same bush as him (one stood on the exact same coord as Deadpool).
I checked that he did not use STEALTH just before (5 rounds) my heros entered the bush.
Deadpool used STEALTH twice during the game, but long before he entered the bush.

I suspect Hero.invisibleBySkill is not set to false as it should at STEALTH duration end, this could give trouble in the first part of Game.updateVisibility() forcing the hero.visible to be set false.

I have not submitted my (CG player name is also cleanrock) code with this huntHiddenHero.
Hopefully you can make a unit test to investigate this.

**Comment by cleanrock** [comment]
Btw, the same code/function worked well versus your (Illedan) cheeky Ironman killing my tower :) .

**Comment by Illedan** [comment]
Thx for letting us know. I'll look at it :)

**Comment by Illedan** [comment]
Did you see this problem again?
We pushed a fix some time back. I'll update the referee if you haven't seen it again.

**Comment by cleanrock** [comment]
I remember seeing a similar situation and was surprised the bug was not to be seen. I think you can close this issue.
