### ISSUE TITLE
Groot target closest hero no matter the range

### ISSUE THREAD

**Issue by tiramon** [Illedan/BOTG-Refree#7]
The statement says : 

> When damaged, they attack the closest Hero, if there is any in 300 range.

 I got a replay (https://www.codingame.com/replay/301373063, Frame 142) where the groot is at y99 and my hero is at y533 and still he runs towards my hero ...

I would say wrong statement or wrong groot behaviour
If i found the right code passage i would say the code miss the 300 limit 

` void aggressiveBehavior(List<Unit> allUnits) {
        Unit attacker = allUnits.stream()
                .filter(u -> u instanceof Hero)
                .sorted((u1, u2) -> u1.distance2(this) < u2.distance2(this) ? -1 : 1)
                .findFirst()
                .get();
        Point target = attacker;
        if (distance2(camp) < Const.AGGROUNITRANGE2) {
            this.attackUnitOrMoveTowards((Unit) target, 0.0);
        } else {
            this.state = CreatureState.runningback;
            this.runTowards(camp);
        }
    }`
 it just takes the closest hero

with `if (distance2(camp) < Const.AGGROUNITRANGE2) {` it only measures the distance to the own camp
which is the following part of the statement

> They chase the targeted hero up to a maximum distance of 300, after which they return to their spawn point.

so in most cases he will strike the enemy even if he is not in 300 range when he got hit

If you are going to fix the code ... this will affect the silver boss

**Comment by Illedan** [comment]
We will fix the statement to explain the actual behaviour. 

Thx for letting us know.
